=== Enochinator/Enochinator.github.io/xml/nosotros.dtd
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (foto, puesto)>
<!ATTLIST empleado
          apellido CDATA #REQUIRED
          nombre CDATA #REQUIRED>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto
          ruta CDATA #REQUIRED>
<!ELEMENT puesto (#PCDATA)>

=== Enochinator/Enochinator.github.io/xml/nosotros.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE empleados SYSTEM "nosotros.dtd">
<empleados>
	<empleado nombre="Alvaro" apellido="Fernandez">
		<foto ruta="../img/alv.jpg"/>
		<puesto>Editor Jefe</puesto>
	</empleado>

	<empleado nombre="Manuel" apellido="Abad">
		<foto ruta="../img/man.jpg"/>
		<puesto>Encargado de revision</puesto>
	</empleado>

	<empleado nombre="Natalia" apellido="Baldonado">
		<foto ruta="../img/nat.jpg"/>
		<puesto>Periodista</puesto>
	</empleado>

	<empleado nombre="Gabriela" apellido="Correa">
		<foto ruta="../img/gab.jpg"/>
		<puesto>Editor</puesto>
	</empleado>

</empleados>
